// dllmain.cpp : Defines the entry point for the DLL application.
#include <Windows.h>
#pragma comment(lib, "User32.Lib")

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
	if (ul_reason_for_call == DLL_PROCESS_ATTACH) {
		MessageBoxA(0, "This is DllMain.", "Simple DLL", MB_OK | MB_ICONWARNING);
	}
    return TRUE;
}

/*
** Visual Studio Configuration Precompiled Header
** Project > Properties > C/C++ > All Option > Precompiled Header > Not Using ...
** => Removed header file and other files generated by VS. Keep only dllmain.cpp or dllmain.c
*/